# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.4-node-browsers
    environment:
      RAILS_ENV: test
      RACK_ENV: test
      BUNDLE_APP_CONFIG: /home/circleci/repo/vendor/bundle
      BUNDLE_PATH: /home/circleci/repo/vendor/bundle/ruby/2.4.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    branches:
      only:
        - master

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo bundle install --jobs=4 --retry=3 --path vendor/bundle

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      - run: 
          name: Set up DB
          command: |
            bundle exec rake db:create db:schema:load --trace
            bundle exec rake db:migrate

      # run tests!
      - run:
          name: run tests
          type: shell
          command: |
            mkdir /tmp/test-results
            bundle exec rails test TESTOPTS="--ci-dir=/tmp/test-results"


      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results